-- CreateEnum
CREATE TYPE "CdmWorksType" AS ENUM ('DIRECT_REPLACEMENT', 'BUILDING_MODIFICATION');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "worksType" "CdmWorksType" NOT NULL DEFAULT 'DIRECT_REPLACEMENT';
