-- CreateEnum
CREATE TYPE "RoleCategory" AS ENUM ('AUTHORISED_PERSON_ENGINEER', 'STATUTORY_OFFICER', 'SENIOR_CONTRACTUAL', 'PROJECT_TEAM');

-- AlterTable
ALTER TABLE "Role" ADD COLUMN     "category" "RoleCategory" NOT NULL DEFAULT 'PROJECT_TEAM';
